### ISSUE TITLE
Implement Requests next, stepIn & stepOut

### ISSUE THREAD

**Issue by Adrodoc** [vanilla-technologies/mcfunction-debugger#62]
Depends on #63.

# TODO
- [x] An attempt to step into an invalid function should step over it.
- [x] Stepping out of function should stop after newline of last line.
- [x] Cache stack trace.
